spring:
  datasource:
    username: tom
    password: 123456
    url: jdbc:mysql://42.192.173.67:3306/wuliu?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: HTML5
    prefix: classpath:/templates/
    enabled: true
    suffix: .html
    content-type: text/html
    check-template: true
    check-template-location: true
  devtools:
    restart:
      enabled: true # ≈‰÷√»»≤ø 
      additional-paths: src/main/java
      exclude: WEB-INF/**
mybatis:
  mapper-locations: classpath:*/mappers/*.xml
  type-aliases-package: com.kuke.wuliu.dao